@startuml
'https://plantuml.com/sequence-diagram

participant Client1
participant Client2
participant Client3
participant MagickOnion

autonumber

rnote over Client1,MagickOnion : ゲームスタート

Client1 -> MagickOnion : 切断
rnote over Client1 : 終了

rnote over MagickOnion : 切断検知

Client2 <- MagickOnion : 切断通知
Client3 <- MagickOnion : 切断通知

rnote over Client2,Client3 : ゲーム中断表示\nメニュー画面遷移

@enduml